"""password_hash added

Revision ID: fa2619f9ee85
Revises: 35532258bf71
Create Date: 2023-08-01 10:51:19.155808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from werkzeug.security import generate_password_hash, check_password_hash

from app import User

# revision identifiers, used by Alembic.
revision = 'fa2619f9ee85'
down_revision = '35532258bf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=True))

    # 데이터 마이그레이션 수행

    # 1. db 접근한다
    bind = op.get_bind()
    session = Session(bind=bind)

    # 2. 데이터 가져온다
    users = session.query(User).all()
    
    # 3. 데이터 변환 과정
    for user in users:
        user.password_hash = generate_password_hash(user.password)

    session.commit()
    session.close()

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
